# Generated by Django 4.0.6 on 2022-07-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkingmodels_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingmodels',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
