# Generated by Django 4.0.6 on 2022-07-16 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_parkingmodels_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkingmodels',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='parkingmodels',
            name='plate',
            field=models.CharField(db_index=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Invalid plate, please use the format AAA-9999', regex='^[A-Z]{3}-[0-9]{4}$')]),
        ),
    ]
