# Generated by Django 4.0.6 on 2022-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_parkingmodels_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingmodels',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parkingmodels',
            name='departure_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
